language: php

matrix:
  - php: 7.2
    env: PTHREADS_VERSION=46962cf9c2d30b6e1e1ea50ca36de3df5d6d4e58
  - php: 7.3
    env: PTHREADS_VERSION=bab25e513ac5445cd7d6d7d36b05a7a0a495f17a
  - php: 7.4
    env: PTHREADS_VERSION=bab25e513ac5445cd7d6d7d36b05a7a0a495f17a

before_script:
 - git clone https://github.com/pmmp/pthreads.git
 - cd pthreads
 - git checkout $PTHREADS_VERSION
 - phpize
 - ./configure
 - make
 - make install
 - cd ..
 - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - composer install --prefer-dist

script:
 - ./vendor/bin/phpstan analyze --no-progress

cache:
 directories:
  - $HOME/.composer/cache/files
  - $HOME/.composer/cache/vcs

notifications:
 email: false
