name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        php: [8.0.22, 8.1.9]

    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: pmmp/setup-php-action@82a44d659bf5046612c69f036af3e14dc32e3fa8
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/composer"
          key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-"

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --no-progress
